FROM linuxserver/smokeping
MAINTAINER Bobbymac
COPY Targets /config/Targets

# If you are only one port 80 service then 80:80 is fine.  In the event that
# you want to run multiple services then a loadbalancer will be needed 
